# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        env:
          REACT_APP_ENV: production
          REACT_APP_BASE_URL: https://fipefacil.thales.work
        run: npm run build
      - name: Test
        run: npm test

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        env:
          REACT_APP_ENV: production
          REACT_APP_BASE_URL: https://fipefacil.thales.work
        run: npm run build
      - uses: actions/vercel-deployment@0.5.1
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
          vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
          assignDomain: "fipefacil.app"
        env:
          REACT_APP_ENV: production
          REACT_APP_BASE_URL: https://fipefacil.thales.work}
